name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: npm install -g pnpm
      
      - run: pnpm install --no-frozen-lockfile

      - name: Reset lockfile
        run: git checkout -- pnpm-lock.yaml

      - name: Install Railway
        if: success()
        run: npm i -g @railway/cli
  
      - name: Deploy backend
        run: railway up -s "lux backend" --detach
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}

      - name: Deploy frontend
        if: success()
        run: railway up -s "lux frontend" --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
